server:
  port: 9000
application:
  opentok:
    apiKey: <Here tokbox API key>
    apiSecret: <Here tokbox API Secret>
    mediaMode: relayed #ROUTED|RELAYED
    archiveMode: always #MANUAL|ALWAYS
    expireTime: 604800 # One week (7 * 24 * 60 * 60)